### ISSUE TITLE
Error when running the WAD

### ISSUE THREAD

**Issue by morgango** [Azure/azure-diagnostics-tools#28]
I am running the following configuration:

```
input {
    azurewadtable
    {
        account_name => "morgango"
        access_key => "(my key goes here)"
        table_name => "LinuxsyslogVer2v0"
    }
    stdin { }
}
```

and getting the following error:

```
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::AzureWADTable account_name=>"morgango", access_key=>"(my key goes here)", 
table_name=>"LinuxsyslogVer2v0", 
enable_metric=>true, 
codec=><LogStash::Codecs::Plain enable_metric=>true, charset=>"UTF-8">,
entity_count_to_process=>100, 
collection_start_time_utc=>"2016-08-08T19:30:43Z", etw_pretty_print=>false, 
idle_delay_seconds=>15>
  Error: undefined method `[]=' for 2016-08-09T20:12:00.530Z %{host} %{message}:LogStash::Event {:level=>:error}
```

Not sure where to start troubleshooting here.  I can connect to the account name and table name with the Microsoft Azure Storage Explorer and see syslog messages arrive in real time, so I know there is data there and it is arriving in near-real-time.

Thanks in advance.

**Comment by mkessel** [comment]
Having the same problem. Did you find a solution?

**Comment by brahmnes** [comment]
What version of logstash and the azurewadtable plugin are you using?
Around line 70, the plugin access the indexer like this:
 70         event = LogStash::Event.new(entity.properties)
 71         event["type"] = @table_name
The [] should be defined for event.

**Comment by brahmnes** [comment]
logstash-input-azurewadtable 0.9.11 is now available on rubygems.org. It uses event.get and event.set instead of [] which should work with logstash 5.0. Please try again.
